version: '3'
services:
  postgres:
    image: postgres
    restart: on-failure
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - PGDATA=/data
    - APP_DATABASE=${DB_NAME}
    ports:
    - "5432:5432"
    container_name: db

  backend:
    build: ./backend
    depends_on:
      - postgres
    restart: on-failure

    env_file:
      - .env    
    ports:
      - "3000:3000"
    container_name: backend
    working_dir: /home/node/app
    user: node
    entrypoint: ["bash" , "-c" , "npm install && npm run start:dev"]

  frontend:
    build: ./frontend
    restart: on-failure
    environment:
      - VUE_APP_BACKEND_URL=${BACKEND_URL}
    ports:
      - '5173:5173'
    container_name: frontend
    depends_on:
      - backend
    user: node
    working_dir: /home/node/app
    entrypoint: ["bash" , "-c" , "npm install && npm run dev"]

networks:
  transcendence:
    driver: bridge