version: '3'

services:
  postgres:
    image: postgres
    restart: on-failure
    volumes:
      - v_db:/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data
      - APP_DATABASE=${DB_NAME}
    ports:
      - "5432:5432"
    container_name: db

  backend:
    image: node
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./backend:/home/node/app

    env_file:
      - .env    
    ports:
      - "3000:3000"
    container_name: backend
    working_dir: /home/node/app
    user: node
    entrypoint: ["bash" , "-c" , "npm install && npm run start:dev"]

  frontend:
    image: node
    restart: on-failure
    environment:
      - VUE_APP_BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./frontend:/home/node/app
    ports:
      - '5173:5173'
    container_name: frontend
    depends_on:
      - backend
    user: node
    working_dir: /home/node/app
    entrypoint: ["bash" , "-c" , "npm install && npm run dev"]

networks:
  transcendence:
    driver: bridge

volumes:
  v_db:
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOL_LOC}
